# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/nest.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/nest.proto\x12 com.nbp.cdncp.nest.grpc.proto.v1\"\x1c\n\nNestConfig\x12\x0e\n\x06\x63onfig\x18\x01 \x01(\t\"1\n\x08NestData\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12\x16\n\x0e\x65xtra_contents\x18\x02 \x01(\t\"\xce\x01\n\x0bNestRequest\x12;\n\x04type\x18\x01 \x01(\x0e\x32-.com.nbp.cdncp.nest.grpc.proto.v1.RequestType\x12>\n\x06\x63onfig\x18\x02 \x01(\x0b\x32,.com.nbp.cdncp.nest.grpc.proto.v1.NestConfigH\x00\x12:\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32*.com.nbp.cdncp.nest.grpc.proto.v1.NestDataH\x00\x42\x06\n\x04part\" \n\x0cNestResponse\x12\x10\n\x08\x63ontents\x18\x01 \x01(\t*#\n\x0bRequestType\x12\n\n\x06\x43ONFIG\x10\x00\x12\x08\n\x04\x44\x41TA\x10\x01\x32\x7f\n\x0bNestService\x12p\n\trecognize\x12-.com.nbp.cdncp.nest.grpc.proto.v1.NestRequest\x1a..com.nbp.cdncp.nest.grpc.proto.v1.NestResponse\"\x00(\x01\x30\x01\x42\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.nest_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_REQUESTTYPE']._serialized_start=378
  _globals['_REQUESTTYPE']._serialized_end=413
  _globals['_NESTCONFIG']._serialized_start=54
  _globals['_NESTCONFIG']._serialized_end=82
  _globals['_NESTDATA']._serialized_start=84
  _globals['_NESTDATA']._serialized_end=133
  _globals['_NESTREQUEST']._serialized_start=136
  _globals['_NESTREQUEST']._serialized_end=342
  _globals['_NESTRESPONSE']._serialized_start=344
  _globals['_NESTRESPONSE']._serialized_end=376
  _globals['_NESTSERVICE']._serialized_start=415
  _globals['_NESTSERVICE']._serialized_end=542
# @@protoc_insertion_point(module_scope)
